Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('config/*.c') + Glob("protocols/*.c")+ Glob("tasks/*.c")+ Glob("core/*.c")
    + Glob("controller/*.c")+ Glob("service/*.c")
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
